# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx book/"

sphinx:
  builder: html
  configuration: book/conf.py
  fail_on_warning: false

# As of 4 Sept 2024, this was taking too long to build. Turning off until we
# decide that we need/want PDF output.
# formats:
#    - pdf

python:
   install:
   - requirements: requirements.txt
